apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-public
  description: asdf
  annotations:
    backstage.io/kubernetes-id: test-public
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: kadel-org/test-public
spec:
  type: api
  system: 
  lifecycle: production
  owner: kadel-org
