apiVersion: marketplace.backstage.io/v1alpha1
kind: Plugin
metadata:
  name: 3scale
  title: APIs with 3scale
  description: Synchronize 3scale content into the Backstage catalog.
  tags:
    - 3scale
    - api
spec:
  categories:
    - API Discovery
  developer: Red Hat
  icon: https://janus-idp.io/images/plugins/3scale.svg

  type: frontend-plugin
  lifecycle: production
  owner: redhat
  description: |
    Synchronize 3scale content into the Backstage catalog.

    3scale Backstage provider allows configuration of one or multiple providers using the `app-config.yaml` configuration file.
  installation:
    markdown: |
      # Installation

      Run the following command to install the 3scale Backstage provider plugin:

      ```console
      yarn workspace backend add @backstage-community/plugin-3scale-backend
      ```

      # Configuration

      3scale Backstage provider allows configuration of one or multiple providers using the `app-config.yaml` configuration file of Backstage.

      ## New Backend Procedure

      1. Use a `threeScaleApiEntity` marker to start configuring the `app-config.yaml` file of Backstage:

        ```yaml title="app-config.yaml"
        catalog:
          providers:
            threeScaleApiEntity:
              dev:
                baseUrl: https://<TENANT>-admin.3scale.net
                accessToken: <ACCESS_TOKEN>
                schedule: # optional; same options as in TaskScheduleDefinition
                  # supports cron, ISO duration, "human duration" as used in code
                  frequency: { minutes: 30 }
                  # supports ISO duration, "human duration" as used in code
                  timeout: { minutes: 3 }
        ```

        **NOTE**
        Make sure to configure the schedule inside the `app-config.yaml` file. The default schedule is a frequency of 30 minutes and a timeout of 3 minutes.

      2. Add the following code to the `packages/backend/src/index.ts` file:

        ```ts title="packages/backend/src/index.ts"
        const backend = createBackend();

        /* highlight-add-next-line */
        backend.add(import('@backstage-community/plugin-3scale-backend'));

        backend.start();
        ```