
on:
  issues:
    types:
    - opened
    - reopened
    - labeled
    - unlabeled

jobs:
  call-shared-workflow:
    permissions:
      issues: write
    uses: kadel-org/shared-workflows/.github/workflows/issue-management.yaml@main
