
on:
  issues:
    types:
    - opened
    - reopened


jobs:
 add-post-ff-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          set -x
          set -e
          gh issue --repo ${{github.repository}} edit ${{github.event.issue.number}} --add-label "post-FF"
          
        env:
          GH_TOKEN: ${{ github.token }}

