
on:
  issues:
    types:
    - opened
    - reopened


jobs:
 label-post-ff:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          set -e
          gh issue --repo ${{github.event.repository.organization}}/${{github.event.repository}} edit ${{github.event.issue.number}} --add-label "post-FF"
          
        env:
          GH_TOKEN: ${{ github.token }}

